### ISSUE TITLE
UnicodeDecodeError with Rutoken ECP after library update 

### ISSUE THREAD

**Issue by nekolyanich** [LudovicRousseau/PyKCS11#37]
* Operating system used: Linux x64
* PyKCS11 version: 1.5.2
* Python version: 3.6
* PKCS#11 library used: librtpkcs11ecp.so

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen
I have Rutoken ECP. 
Before last library update (with auto string decoding) on v1.4.4 token_info was:
```
(Pdb) pp token_info.to_dict()
{'firmwareVersion': (23, 2),
 'flags': ['CKF_RNG',
           'CKF_LOGIN_REQUIRED',
           'CKF_USER_PIN_INITIALIZED',
           'CKF_TOKEN_INITIALIZED',
           'CKF_SO_PIN_TO_BE_CHANGED'],
 'hardwareVersion': (20, 5),
 'label': b'Rutoken ECP <no label>          ',
 'manufacturerID': b'Aktiv Co.                       ',
 'model': b'Rutoken ECP     ',
 'serialNumber': b'37354ce9        ',
 'ulFreePrivateMemory': 60032,
 'ulFreePublicMemory': 60032,
 'ulMaxPinLen': 32,
 'ulMaxRwSessionCount': 0,
 'ulMaxSessionCount': 0,
 'ulMinPinLen': 6,
 'ulRwSessionCount': 0,
 'ulSessionCount': 0,
 'ulTotalPrivateMemory': 65536,
 'ulTotalPublicMemory': 65536,
 'utcTime': b'versionr.\x00\x00\x00\xda\x07_c'}

```

### Describe what _did_ happen.

On v1.5.2 it raise:
 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 4: invalid start byte`

I've modify a bit you code for ignore errors:

```
 diff --git a/src/pykcs11.i b/src/pykcs11.i
index f15b023..8eac4be 100644
--- a/src/pykcs11.i
+++ b/src/pykcs11.i
@@ -58,7 +58,7 @@ using namespace std;
   #ifdef Py_USING_UNICODE
    $result = PyBytes_FromStringAndSize((const char*)($1.m_str.c_str()),(int)($1.m_str.size()));
   #else
-   $result = PyUnicode_FromStringAndSize((const char*)($1.m_str.c_str()),(int)($1.m_str.size()));
+   $result = PyUnicode_Decode((const char*)($1.m_str.c_str()),(int)($1.m_str.size()), "utf-8", "ignore");
   #endif
 }
```
And it works for me now:
```
(Pdb) pp token_info.to_dict()
{'firmwareVersion': (23, 2),
 'flags': ['CKF_RNG',
           'CKF_LOGIN_REQUIRED',
           'CKF_USER_PIN_INITIALIZED',
           'CKF_TOKEN_INITIALIZED',
           'CKF_SO_PIN_TO_BE_CHANGED'],
 'hardwareVersion': (20, 5),
 'label': 'Rutoken ECP <no label>          ',
 'manufacturerID': 'Aktiv Co.                       ',
 'model': 'Rutoken ECP     ',
 'serialNumber': '37354ce9        ',
 'ulFreePrivateMemory': 60032,
 'ulFreePublicMemory': 60032,
 'ulMaxPinLen': 32,
 'ulMaxRwSessionCount': 0,
 'ulMaxSessionCount': 0,
 'ulMinPinLen': 6,
 'ulRwSessionCount': 0,
 'ulSessionCount': 0,
 'ulTotalPrivateMemory': 65536,
 'ulTotalPublicMemory': 65536,
 'utcTime': 'j\x01|\x01\x01}\x02|\x02s\x1et\x02d\x01'}
```
Can you make this behavior in upstream?

**Comment by LudovicRousseau** [comment]
What string contains the problematic 0x83 byte in your case?

**Comment by nekolyanich** [comment]
I'm sorry about posted error with 0x83. I'm reproduced it for you:
```

    token_info = pkcs11.getTokenInfo(slot)
  File "/home/nekolyanich/.venv/cryptokey_old/lib/python3.6/site-packages/PyKCS11/__init__.py", line 608, in getTokenIn
fo
    t.utcTime = tokeninfo.GetUtcTime()
  File "/home/nekolyanich/.venv/cryptokey_old/lib/python3.6/site-packages/PyKCS11/LowLevel.py", line 859, in GetUtcTime
    return _LowLevel.CK_TOKEN_INFO_GetUtcTime(self)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 12: invalid continuation byte

```
Yes this problem with not valid UTF-8 string.

**Comment by nekolyanich** [comment]
But that bad string not in label. Bad byte in utcTime/

**Comment by LudovicRousseau** [comment]
According to PKCS#11 https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html

> utcTime
current time as a character-string of length 16, represented in the format YYYYMMDDhhmmssxx (4 characters for the year;  2 characters each for the month, the day, the hour, the minute, and the second; and 2 additional reserved ‘0’ characters).  The value of this field only makes sense for tokens equipped with a clock, as indicated in the token information flags (see below)

Your PKCS#11 library returns b'versionr.\x00\x00\x00\xda\x07_c' which is NOT in the correct format. You should report this problem to the library provider.

On my Python 3 I get:
```
>>> utc=b'versionr.\x00\x00\x00\xda\x07_c'
>>> utc
b'versionr.\x00\x00\x00\xda\x07_c'
>>> utc.decode("utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 12: invalid continuation byte
>>> utc.decode("utf-8", "ignore")
'versionr.\x00\x00\x00\x07_c'
```
It is strange you get `'utcTime': 'j\x01|\x01\x01}\x02|\x02s\x1et\x02d\x01'` on your side.

**Comment by LudovicRousseau** [comment]
Fixed in https://github.com/LudovicRousseau/PyKCS11/commit/84b921bc74b2416c977b852fe430ea9649342e04

Thanks
