### ISSUE TITLE
ModuleNotFoundError: No module named 'PyKCS11._LowLevel'

### ISSUE THREAD

**Issue by Neywiny** [LudovicRousseau/PyKCS11#59]
#### Your system information

* Operating system used: Ubuntu 18.04
* PyKCS11 version: whatever is most recent at this time
* Python version: 3.6 and 2.7.15
* PKCS#11 library used: most recent at this time

#### Please describe your issue in as much detail as possible:
In trying to import the module after building and installing (with sudo) I get

Traceback (most recent call last):
  File "/home/dylan/Documents/smartcard/PyKCS11/PyKCS11/LowLevel.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'PyKCS11._LowLevel'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/Documents/smartcard/PyKCS11/PyKCS11/__init__.py", line 20, in <module>
    import PyKCS11.LowLevel
  File "/home/user/Documents/smartcard/PyKCS11/PyKCS11/LowLevel.py", line 17, in <module>
    _LowLevel = swig_import_helper()
  File "/home/user/Documents/smartcard/PyKCS11/PyKCS11/LowLevel.py", line 16, in swig_import_helper
    return importlib.import_module('_LowLevel')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_LowLevel'
```

I saw [this post](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741329) but the guy fixed it without saying how. Same error exists with 3.6 and 2.7.15. I've tried 'make rebuild' and build/install again, same thing.

#### Steps for reproducing this issue:

1. clone repo
2. install repo
3. import module

**Comment by karthikams** [comment]
@Neywiny How did you fix this issue? I didn't understand "Just go out of the directory".

**Comment by LudovicRousseau** [comment]
Do not run python from inside the PyKCS11 source code directory because the `import PyKCS11` will fail.
"Just go out of the directory"
