### ISSUE TITLE
The "--sign" and "--decrypt" options of "dumpit.py" cause tracebacks.

### ISSUE THREAD

**Issue by srsross** [LudovicRousseau/PyKCS11#87]
# Your system information

* Operating system used: Red Hat Enterprise Linux 8.4
* Python virtual environment: 
```
$ rpm -q python3-virtualenv
python3-virtualenv-15.1.0-19.module+el8.1.0+3514+14e79d98.noarch
$ virtualenv --version
15.1.0
```
* PyKCS11 version:
```
]$ pip show PyKCS11
Name: PyKCS11
Version: 1.5.10
Summary: A Full PKCS#11 wrapper for Python
Home-page: https://github.com/LudovicRousseau/PyKCS11
   ...
```
* Python version:
```
$ python --version
Python 3.6.8
```
* PKCS#11 library used:
```
$ rpm -q opensc
opensc-0.20.0-4.el8.x86_64
```
* PyKCS#11 Git repository commit:
```
$ git show |head -n 1
commit bc6d33ce6000cd8ef005e360abe8cbb8224cb8b3
```

# Please describe your issue in as much detail as possible:
I expect that the `--sign` and `--decrypt` options of the (high-level) `dumpit.py` Python script should sign and decrypt, respectively.
However, both options cause Python tracebacks.

# Steps for reproducing this issue:
Here is an example of a traceback when using `--sign` (with the PIN and other information obscured):
```
(Venv-PyKCS11) $  python ~/Scripts/PyKCS11/samples/dumpit.py -c /usr/lib64/opensc-pkcs11.so --pin NNNNNNNN --sign
using PKCS11 lib: /usr/lib64/opensc-pkcs11.so
Library manufacturerID: OpenSC Project
Available Slots: 1 [0]
Slot no: 0
  slotDescription: SCM Microsystems Inc. SCR 3310 [CCID Interface] (533115492115...
  manufacturerID : Identive
  hardwareVersion: 0.00
  firmwareVersion: 0.00
  flags          : CKF_TOKEN_PRESENT, CKF_REMOVABLE_DEVICE, CKF_HW_SLOT
TokenInfo
  label:  <.....>
  manufacturerID: piv_II
  model: PKCS#15 emulated
Opened session 0x5606D1B85F50

Found 20 objects: [94587288302336, 94587288302624, 94587288302912, 94587288302432, 94587288302720, 94587288303520, 94587288302528, 94587288302816, 94587288306272, 94587288306752, 94587288306848, 94587288306944, 94587288306368, 94587288306464, 94587288306560, 94587288306656, 94587288307040, 94587288307136, 94587288307232, 94587288307328]

==================== Object: 1/20 (94587288302336) ====================
* Signing with object 0x5606D1B83300 following data: b'12345678901234567890'
Traceback (most recent call last):
  File "/home/<...>/Scripts/PyKCS11/samples/dumpit.py", line 212, in <module>
    sx = eval(b"0x" + "".join("%02X" % c for c in signature))
TypeError: can't concat str to bytes
```

Following is the output and traceback when using the `--decrypt` option on the command line:
```
(Venv-PyKCS11) $ python ~/Scripts/PyKCS11/samples/dumpit.py -c /usr/lib64/opensc-pkcs11.so --pin NNNNNNNN --decrypt
using PKCS11 lib: /usr/lib64/opensc-pkcs11.so
Library manufacturerID: OpenSC Project
Available Slots: 1 [0]
Slot no: 0
  slotDescription: SCM Microsystems Inc. SCR 3310 [CCID Interface] (533115492115...
  manufacturerID : Identive
  hardwareVersion: 0.00
  firmwareVersion: 0.00
  flags          : CKF_TOKEN_PRESENT, CKF_REMOVABLE_DEVICE, CKF_HW_SLOT
TokenInfo
  label: <......>
  manufacturerID: piv_II
  model: PKCS#15 emulated
Opened session 0x55738A93A230

Found 20 objects: [93954734520048, 93954734520336, 93954734520624, 93954734520144, 93954734520432, 93954734521232, 93954734520240, 93954734520528, 93954734523984, 93954734524464, 93954734524560, 93954734524656, 93954734524080, 93954734524176, 93954734524272, 93954734524368, 93954734524752, 93954734524848, 93954734524944, 93954734525040]

==================== Object: 1/20 (93954734520048) ====================
* Decrypting with 0x55738A9376F0 following data: 12345678901234567890
padded:
Traceback (most recent call last):
  File "/home/<...>/Scripts/PyKCS11/samples/dumpit.py", line 253, in <module>
    print(dump(padded))
  File "/home/<...>/Scripts/PyKCS11/samples/dumpit.py", line 49, in dump
    hexa = " ".join(["%02X" % ord(x) for x in s])
  File "/home/<...>/Scripts/PyKCS11/samples/dumpit.py", line 49, in <listcomp>
    hexa = " ".join(["%02X" % ord(x) for x in s])
TypeError: ord() expected string of length 1, but int found
```

**Comment by srsross** [comment]
Thanks for commit `13f0b16`.  (I see also your removal of the signing and decryption code in commit `c6e00ae`, and your recommendation to use `rsa_encrypt.py` and `encrypt.py`. )

After including the first commit, I no longer see any Python tracebacks.  So far, so good.  But I now see behavior that I don't understand.

For signing, the signing test with the first private-key object on my smart card succeeds (as expected), but the signing with the second private-key on the card fails with:
```
* Signing with object 0x5567C907BD50 following data: b'12345678901234567890'
Sign failed, exception: CKR_USER_NOT_LOGGED_IN (0x00000101)

logout failed, exception: CKR_USER_NOT_LOGGED_IN (0x00000101)
```
Because I was signed in for the first successful signing/verification, I would expect to still be signed into the session on the card for the second private-key.

For decryption, the `dumpit.py` error for the first private-key is:
```
Decrypt failed, exception: CKR_GENERAL_ERROR (0x00000005)
```
Are these two PKCS#11 errors  expected after including (just) your first commit?

Thanks in advance for any insight that you can offer,
-- Steve Ross

**Comment by LudovicRousseau** [comment]
I also get `CKR_GENERAL_ERROR` for decryption if I use SoftHSM PKCS#11 library.
For `CKR_USER_NOT_LOGGED_IN` I guess you should enter the PIN (again).

For all these reasons the code in `dumpit.py` was problematic. I preferred to remove it and not support it any more.
